bit-bots/wolfgang_robot

- wolfgang_description/launch/wolfgang_rviz.launch
- wolfgang_description/launch/wolfgang_standalone.launch
PR which should fix https://github.com/bit-bots/wolfgang_robot/issues/6
rviz launch only launches rviz with the wolfgang config
standalone launches the fake controller to have the robot in rviz and to play around with the model
> fixed wolfgang launch files

- wolfgang_description/urdf/wolfgang_basler.urdf.xacro
imu was not published in simulation due to wrong frame name. this is fixed and was tested
the orientation of the imu sensor seems to be not correct. Changing the rpy values in the <pose> of the imu plugin in the URDF doesn't seem to change anything.
This pull request can be merged like this to repair the IMU, but it would maybe good to verify first if the rotation is now correct
> fixed imu frame so that it is published again

- wolfgang_moveit_config/config/wolfgang.srdf
The head visual model was reintroduced in #17. This pull request disables collision between head and torso to make collision detection possible in the dynamic kick.
> moveit_config: disable collisions between head and torso

- wolfgang_moveit_config/config/kinematics.yaml
They are now unsupported by kinematics solvers, a warning is issued when the parameter exists.
> moveit_config: remove attempts from kinematics.yaml

- wolfgang_animations/animations/falling/falling_back.json
- wolfgang_animations/animations/falling/falling_front.json
- wolfgang_animations/animations/falling/falling_left.json
- wolfgang_animations/animations/falling/falling_right.json
- wolfgang_animations/package.xml
As mentioned in bit-bots/bitbots_motion#98, this pull request removes the pause after the falling animations.
> animations: remove pause in falling animations

- wolfgang_animations/animations/falling/falling_front.json
- wolfgang_animations/package.xml
The falling animation is not fully executed without the pause at the end. Therefore, this PR adds a brief pause of 0.1 seconds after the animation.
> add pause after falling_front

- wolfgang_webots_sim/CMakeLists.txt
Docs fail to build before this PR because documentation is built twice
- ~[ ] Test on the robot~
> remove double enabling of bibots docs causing docs to fail to build

- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_controller.py
In the webots controller, the joint positions are published twice, once in `publish_joint_states` and once in `get_joint_state_msg`. This PR removes the undesired side effect from `get_joint_state_msg`.
> webots: fix duplicate publishing of joint positions

- wolfgang_description/urdf/robot.urdf
This reduces the size of the neck SEA to avoid a collision between the head and the torso.
bit-bots/bitbots_behavior#85
> Reduce SEA size to avoid collisions

- wolfgang_webots_sim/worlds/robot_supervisor.wbt
Remove the second controller from the robot supervisor world that was added in #123 on accident.
> Remove other controller from robot supervisor world

- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_robot_controller.py
Fixes timestamp of right foot pressure sensor in `webots_robots_controller`.
~- [ ] Run `catkin build`~
~- [ ] Write documentation~
~- [ ] Create issues for future work~
~- [ ] Test on the robot~
> Fix right pressure stamp

- wolfgang_webots_sim/protos/Wolfgang.proto
This pull request adds the `[hand]` tags required for the model submission and changes the default controller to `player`. The `player` controller is the controller serving the robocup api. I don't know if this controller will be set automatically or if it is required to manually set it.
> Adapt proto file for RoboCup model submission

- Jenkinsfile
- wolfgang_webots_sim/.rdmanifest
Add jenkins configuration for the `wolfgang_webots_sim` package as well as an `.rdmanifest` file which makes it installable as a dependency.
merge https://github.com/bit-bots/bitbots_tools/pull/107 after this
> Add wolfgang_webots_sim to CI

- wolfgang_robocup_api/config/team.json
This adds a team.json file for the RoboCup with four robots in four different positions. They are set up as a goalie, two defense players, and one offense player. I did not test the reentryStartingPose yet, because my autoreferee does not seem to work correctly at the moment.
Closes issue #133 (I think. There are four robots and I think @Flova changed the orientation such that the robot no longer falls at the beginning. However, they are not closer to the line)
> Add team.json

- wolfgang_robocup_api/launch/wolfgang_robocup_api_bridge.launch
- wolfgang_robocup_api/src/wolfgang_robocup_api/wolfgang_robocup_api.py
Lets api try to reconnect in a loop instead of dying and being respawned through roslaunch. Just to improve the terminal spam
> fix api restart

- wolfgang_robocup_api/docker/Dockerfile
This PR adds a `sed` function to sed `respawn="true"` for all nodes except for the api bridge, which is set to `required="True"` (see #174). In addition, the docker file is improved so that it can be built with cache and the build only takes ~5 minutes. Pushing time is probably also improved.
> Set respawn true in docker, improve caching

- wolfgang_robocup_api/scripts/start.sh
This adds the ROBOCUP_MIRROR_SERVER_IP as an environment variable to `start.sh`. When set to `127.0.0.1`, the team comm will be started in local mode, else it will connect to the udp bouncer on the given server. Must be merged after bit-bots/humanoid_league_misc#91.
> Add ROBOCUP_MIRROR_SERVER_IP to start.sh

- wolfgang_robocup_api/config/team.json
With this PR, the shootoutStartingPose of the first robot is adapted to be closer to the ball. The other robots are set to their normal starting poses for the shootout and for the goalie's position.
> Set shootoutStartingPose correctly

- wolfgang_robocup_api/docker/Dockerfile
The RoboCup API was previously set to `required="true"`, but since the software is not automatically restarted, this does not have the desired effect. This PR changes it to `respawn="true"`, like all other nodes.
Closes #174.
> Set respawn="true" for the robocup api in docker

- wolfgang_webots_sim/protos/Wolfgang.proto
Since we changed from force 3d to force in the proto, the cleats have not been working correctly since the axis was not oriented correctly (see https://cyberbotics.com/doc/reference/touchsensor#force-sensors)
> fix orientation of cleats so force sensors work

- wolfgang_webots_sim/launch/simulation.launch
The Dockerfile currently does very dirty stuff to set respawn to true for all nodes. The replacing script is only looking in the same line as the opening `<node` tag, which does not work when the tag is set in the next line.
> Fix location of required/respawn for docker

- wolfgang_robocup_api/docker/Dockerfile
We recently had some problems that would have been found by our tests, this changes the docker build process to include running tests.
Some tests for webots had to be deleted because webots is not installed in the docker container.
> Execute tests in docker

- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_robot_controller.py
Adds torque control to the webots sim controller.
The change is required for bit-bots/bitbots_motion#298.
This change is not used in the production docker, so it should not break the system.
> Add torque control to webots sim

- wolfgang_webots_sim/scripts/setenvs.sh
This pull request makes `setenvs.sh` respect an existing `WEBOTS_HOME` variable and support Python 3.8.
> Fix setenvs.sh for local webots installation and python 3.8

- wolfgang_robocup_api/docker/Dockerfile
In the docker, we never test the webots test because there is no webots installed. Currently, the only way to do that is to remove these tests manually. This removes a new webots test in the walking that was recently added.
> Remove new webots test from Docker

- wolfgang_pybullet_sim/src/wolfgang_pybullet_sim/ros_interface.py
- wolfgang_pybullet_sim/src/wolfgang_pybullet_sim/simulation.py
Fixes imu orientation so that it is in relation to gravity vector and not global coordinate frame
closes https://github.com/bit-bots/wolfgang_robot/issues/122
> fix imu orientation

- wolfgang_moveit_config/config/kinematics.yaml
For LeftLeg, RightLeg, LeftArm, RightArm and Head we need bio_ik, but for Arms, Legs and All no solver is required as we don't use the groups in the kinematics plugin. This speeds up loading of moveit.
> Speed up loading of moveit by removing unneeded kinematics solvers

- wolfgang_robocup_api/launch/record_bag.launch
- wolfgang_robocup_api/launch/robocup_teamplayer.launch
Remove nth_image from record bag as it is not used
> Remove nth_image from record bag

- wolfgang_moveit_config/config/kinematics.yaml
- Change moveit config to use bio_ik all the time.
Closes https://github.com/bit-bots/bitbots_motion/issues/373
> Use bio_ik instead of the KDL default for all move groups

- wolfgang_webots_sim/protos/Wolfgang.proto
Add tagged solids to wolfgang proto to comply with HLVS specifications:
https://humanoid.robocup.org/wp-content/uploads/v-hsc_model_specification.pdf
> Add tagged solids to wolfgang proto

- wolfgang_robocup_api/docker/Dockerfile
The additional packages are no longer in the requirements file but are installed via rosdep. However, I don't want to use rosdep in the container because it will install some packages that are not needed and makes caching impossible.
Also, the installation of numpy via pip has to be removed because a breaking change has not been addressed in all packages we use.
bit-bots/bitbots_meta#168 makes the change necessary.
> Fix docker build with updated requirements file

- wolfgang_webots_sim/CMakeLists.txt
- wolfgang_webots_sim/launch/simulation.launch
- wolfgang_webots_sim/scripts/setenvs.sh
Removes the need for sourcing the `setenvs.sh` script before running the simulator (non-hlvs player). This reduces complexity.
- Set the appropriate env variables in the launch file
- Remove the old script
I tested this on my machine and it worked fine. I removed some lines were not needed imo., but I want to get a second opinion on this @timonegk.
> Port setenvs.sh script to a launch file

- wolfgang_robocup_api/package.xml
Add `rosbag2` dependency as it is needed to record rosbags using the CLI.
Needs also to be done in bit-bots/bitbots_misc/pull/190
> Fix: Add `rosbag2` dependency

- wolfgang_moveit_config/config/kinematics.yaml
This reverts commit c061f0519a9a038191ef92071313f2cd19ea98c1.
Closes #250
> Revert "Use bio_ik instead of the KDL default for all move groups"

- wolfgang_robocup_api/docker/Dockerfile
* Use `requirements/common.txt` instead of previous `requirements.txt`
* This removes the need to manipulate the file before installing with pip
bit-bots/bitbots_meta/pull/198
> Update: Dockerfile: Use common pip requirements
