- wolfgang_description/urdf/wolfgang.urdf.xacro
- wolfgang_description/urdf/wolfgang_basler.urdf.xacro
- wolfgang_description/urdf/wolfgang_logitech.urdf.xacro
This pull request adds an urdf for the Basler camera. The correct urdf gets selected by the load_robot_description launch file (Pull request in bitbots_misc).
> Basler cam urdf

- wolfgang_animations/animations/motion/stand_up_front_fast.json
Updated the stand up front animation.
> faster stand up front animation, adaptions to new camera

- wolfgang_animations/animations/motion/stand_up_front.json
- wolfgang_description/launch/wolfgang_rviz.launch
- wolfgang_description/launch/wolfgang_standalone.launch
just added some extra pause to make it more stable
> Fix standup

- wolfgang_description/urdf/wolfgang_basler.urdf.xacro
- wolfgang_description/urdf/wolfgang_logitech.urdf.xacro
> wolfgang_description: correct location of imu

- wolfgang_moveit_config/config/kinematics.yaml
- wolfgang_moveit_config/package.xml
Just changes config so that leg IK is computed using KDL
https://github.com/bit-bots/bitbots_motion/pull/120
> change leg IK to KDL

- wolfgang_description/config/wolfgang.rviz
- wolfgang_description/package.xml
#12 
``roslaunch wolfgang_description wolfgang_rviz.launch``
- ~[ ] Run `catkin build`~
- ~[ ] Write documentation~
- ~[ ] Create issues for future work~
- ~[ ] Test on the robot~
> rviz config

- wolfgang_pybullet_sim/CMakeLists.txt
- wolfgang_pybullet_sim/cfg/sim.cfg
- wolfgang_pybullet_sim/launch/simulation.launch
- wolfgang_pybullet_sim/package.xml
- wolfgang_pybullet_sim/src/wolfgang_pybullet_sim/ros_interface.py
- wolfgang_pybullet_sim/src/wolfgang_pybullet_sim/simulation.py
Add filtered option for simulated pressure sensors
- ~[ ] Create issues for future work~
- ~[ ] Test on the robot~
> Foot pressure filter

- wolfgang_webots_sim/package.xml
- wolfgang_webots_sim/protos/Wolfgang.proto
- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_controller.py
Adds force sensors to the feet.
https://github.com/bit-bots/wolfgang_robot/issues/52
> webots force sensors

- wolfgang_description/config/wolfgang.rviz
- wolfgang_description/urdf/additionalURDF.txt
- wolfgang_description/urdf/robot.urdf
- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_controller.py
renames image message in order to be compatible with changes in bitbots_vision
> renamed image_raw to camera/image_proc

- wolfgang_webots_sim/launch/simulation.launch
- wolfgang_webots_sim/package.xml
- wolfgang_webots_sim/protos/Wolfgang.proto
- wolfgang_webots_sim/scripts/start.sh
- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_controller.py
Fix for IMU and camera in webots.
Add correct location for torso IMU, add head IMU. Add camera info. Changed parameters of head servos  to make rotation more realistic
> webots: fix imu and camera

- README.md
Provide links to CAD files and electronics of this robot
> Create README with additional links

- wolfgang_moveit_config/config/wolfgang.srdf
This disables some collisions in the legs that were probably introduced in the new urdf.
Required for https://github.com/bit-bots/bitbots_behavior/pull/85.
> disable some collisions

- wolfgang_webots_sim/launch/single_robot_controller.launch
sensor frames are not set correctly before this PR
> webots_sim: fix sensor frame prefixes

- wolfgang_webots_sim/launch/simulation.launch
- wolfgang_webots_sim/launch/single_robot_controller.launch
> webots_sim: fix tf_prefix for single robot

- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_robot_controller.py
> webots_sim: respect velocities and accelerations

- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_robot_controller.py
- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_robot_supervisor_controller.py
- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_supervisor_controller.py
- wolfgang_webots_sim/worlds/robot_supervisor.wbt
- Add methods to get and set the ball position and to get the ball velocity
- Add a RobotSupervisorController that controls a single robot and is supervisor of the simulation
- Add some comments
> Some adaptions to the webots controller

- .gitignore
- wolfgang_animations/animations/falling/falling_front.json
- wolfgang_description/urdf/config.json
- wolfgang_moveit_config/config/kinematics.yaml
- wolfgang_pybullet_sim/cfg/sim.cfg
- wolfgang_pybullet_sim/config/config.yaml
- wolfgang_pybullet_sim/src/wolfgang_pybullet_sim/ros_interface.py
- wolfgang_pybullet_sim/src/wolfgang_pybullet_sim/simulation.py
Manually cleaned up version of https://github.com/bit-bots/wolfgang_robot/pull/103
> manually put changes on new branch

- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_robot_controller.py
- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_robot_supervisor_controller.py
- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_supervisor_controller.py
This adds a parameter to set a base namespace for the webots simulator controller. I know that this is not a pretty solution, but it is currently the best solution for the parameter search and reinforcement learning.
> Add base_ns parameter to be used in optimization

- wolfgang_description/docs/index.rst
- wolfgang_webots_sim/docs/index.rst
Just some documentation.
closes #87
> wrote doc for urdf proto stuff

- wolfgang_webots_sim/launch/imu_filter_sim.launch
Improve IMU parameters (disable bias estimation, decrease gain_acc).
> Improve imu parameters

- wolfgang_webots_sim/protos/Wolfgang.proto
- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_robot_controller.py
- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_supervisor_controller.py
- wolfgang_webots_sim/worlds/robot_supervisor.wbt
This adds a few things to webots:
* l_sole and r_sole objects
* get_robot_velocity and get_link_velocity functions
* make sensor suffix a member variable to access it from outside
* update robot_supervisor world with new environment
> Webots sim improvements for reinforcement learning

- wolfgang_animations/animations/motion/walkready.json
- wolfgang_animations/animations/motion/walkready_sim.json
* Change both the sim and the normal walkready so that the arms are less visible in the camera image
* The files are autogenerated by the dynup
> Change walkready pose

- README.md
> include link to video in readme

- wolfgang_description/urdf/robot.urdf
In the proto, the knee velocities are 3.87, that should be the same in the urdf.
> Change knee velocities to values from proto

- wolfgang_robocup_api/config/bitbots_walk.json
- wolfgang_robocup_api/docker/Dockerfile
- wolfgang_robocup_api/launch/robocup_walk.launch
* A launch file launching the motion stack and giving a walking command is added
* unneeded packages are removed from the dockerfile
* needed packages are added to the dockerfile
* A configuration file for the walking behavior including the launch command and the start poses was added
> Fixes for the robocup model submission

- wolfgang_robocup_api/config/bitbots_walk.json
The previous config used the old values.
> Fix docker commands in config file

- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_robot_controller.py
Fixes following error that is spamed into terminal by webots when the robot moves
```
[ERROR] [1621953879.322372327, 60.000000000]: Ignoring transform for child_frame_id "base_link" from authority "unknown_publisher" because of a nan value in the transform (-nan -nan -nan) (-nan -nan -nan -nan)
Error:   Error:   TF_DENORMALIZED_QUATERNION: Ignoring transform for child_frame_id "base_link" from authority "unknown_publisher" because of an invalid quaternion in the transform (-nan -nan -nan -nan)TF_NAN_INPUT: Ignoring transform for child_frame_id "base_link" from authority "unknown_publisher" because of a nan value in the transform (-nan -nan -nan) (-nan -nan -nan -nan)
```
It comes from all acceleration values being zero.
> webots: fix accel bug

- wolfgang_robocup_api/src/wolfgang_robocup_api/wolfgang_robocup_api.py
Same as #141 but for the robocup api.
> Fix imu acceleration zero problem in robocup api client

- wolfgang_robocup_api/docker/Dockerfile
Use cuda image and install pytorchyolo for our vision.
> Use cuda as base image

- wolfgang_robocup_api/config/config.yaml
> Change image frame step to 16ms

- wolfgang_description/urdf/robot.urdf
- wolfgang_webots_sim/protos/Wolfgang.proto
- wolfgang_webots_sim/protos/Wolfgang_textures/WolfgangMarker.proto
This PR applies the feedback from the robot model review.
Two changes are applied to the cleats:
1. The cleats are modeled with a 'Capsule' solid instead of two separate solids.
2. The height of the cleats is increased by 4mm to avoid that the foot plate touches the ground, simplifying the contact point calculation.
These changes drastically increase the performance, on my computer it is more than doubled.
Should the height change of the cleats also be applied to the urdf?
> Apply robot model feedback

- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_supervisor_controller.py
> only publish model states if requested

- wolfgang_webots_sim/worlds/walk_optim_wolfgang.wbt
Compared the current Robocup release with our test worlds and this parameter is different. I dont know it makes any real difference though.
> adapt world to robocup values

- wolfgang_robocup_api/scripts/start.sh
This sets our team id to 7 like it is configured in the game controller.
> Set our team id correctly

- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_supervisor_controller.py
Allows to set ball position and robot pose
https://github.com/bit-bots/bitbots_msgs/pull/22
https://github.com/bit-bots/bitbots_tools/pull/111
> webots: set ball position and robot pose

- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_supervisor_controller.py
> Fix usage of removed method

- wolfgang_robocup_api/config/bitbots_walk.json
Changes poses, I tested them. It mostly fixes the referee bug.
> Adapt json file with robot poses for the competition

- wolfgang_robocup_api/config/bitbots_walk.json
Places the robot on a safer position, so it never accidentally tuches the field during the penalty.
> Place robot on safer position

- wolfgang_robocup_api/src/wolfgang_robocup_api/wolfgang_robocup_api.py
* Add deep copy with a mutex to prevent the joint commands from changing during the sending. This is needed because python subs are running in their own threads
We survive a whole game now. Yay
> Makes robocup api thread safe (hopefully)

- wolfgang_webots_sim/src/wolfgang_webots_sim/webots_supervisor_controller.py
> Remove usage of old class

- wolfgang_robocup_api/config/team.json
> fix penalty start pose

- wolfgang_robocup_api/config/team.json
- wolfgang_webots_sim/protos/Wolfgang.proto
Sets initial position to something more stable.
> initial posture webots

- wolfgang_description/urdf/robot.urdf
- wolfgang_webots_sim/protos/Wolfgang.proto
Increase head limits to maximum in rules.
> fix head position to correct limits

- wolfgang_robocup_api/config/team.json
Set the robots to the goal/penalty mark.
> Adds the propper penalty kick pose

- wolfgang_robocup_api/CMakeLists.txt
- wolfgang_robocup_api/src/wolfgang_robocup_api/wolfgang_robocup_api.py
Skips, if received message is invalid
Remove unnecessary include in CMake
~- [ ] Write documentation~
~- [ ] Create issues for future work~
~- [ ] Test on the robot~
> RoboCup API: hande invalid message

- wolfgang_robocup_api/config/team.json
This changes the team.json to use two offense players instead of two defense players
> Change to two offense players

- wolfgang_robocup_api/docker/Dockerfile
Use make pull-init to pull all submodules correctly in docker container.
> Use make pull-init in docker

- wolfgang_robocup_api/scripts/start.sh
This change adds a `--team` argument to the `start.sh` script. It makes it possible to launch a robot with another team id than the default team id. This is useful for playing two software stacks against each other.
> Add --team argument to start.sh

- wolfgang_robocup_api/scripts/start.sh
> Fix variable access in start.sh

- wolfgang_animations/animations/motion/goalie_falling_center.json
- wolfgang_animations/animations/motion/goalie_falling_left.json
- wolfgang_animations/animations/motion/goalie_falling_right.json
- wolfgang_animations/animations/motion/goalie_prepare_arms.json
- Remove pause because there is no longer a risk of standing up
- Increase time of arm animation to avoid instability due to a fast movement
> Small fixes in goalie animations

- wolfgang_robocup_api/config/team.json
since the rules changed we can only use 3 players instead of 4
We should notify our team when this is merged, so they can update the team.json in their webots folders.
> changes team json to only have 3 players and sensible positions/roles

- wolfgang_robocup_api/config/team.json
> goalie instead of defender and shootout pos

- wolfgang_animations/animations/motion/cheering.json
> slow down cheering a bit so we are less likely to fall

- wolfgang_robocup_api/src/wolfgang_robocup_api/wolfgang_robocup_api.py
This pull request fixes the problem that only the last joint command was sent to the api. Now, the messages are merged to include all previously received data.
In addition, torque control can now be used by to control the actuators by setting the `accelerations` field and not sending any position goals.
> Fix merging of joint commands, add torque control

- wolfgang_robocup_api/launch/record_bag.launch
- Reduces the rate of recorded images in rosbags
- Remove unused argument (using it correctly would be complicated)
Too large rosbags > 10GB
> Reduce the image rate in rosbages

- wolfgang_webots_sim/scripts/imu_lut_gen.py
> add look up table script

- wolfgang_robocup_api/config/team.json
* Change start and restart positions
Note that this `team.json` needs to be submitted again!
> Tweak team.json for adult size field

- wolfgang_robocup_api/config/team.json
This reverts commit 5f59a08e94a5aebee8d1c355931a75dfb0bfba3c.
> Revert "Tweak team.json for adult size field."

- wolfgang_robocup_api/config/team.json
> return of the defense

- wolfgang_webots_sim/scripts/setenvs.sh
> fix typo in setenvs script

- wolfgang_pybullet_sim/src/wolfgang_pybullet_sim/simulation.py
> Fixes a bug where velocities were saved as positions

- wolfgang_webots_sim/CMakeLists.txt
- wolfgang_webots_sim/package.xml
I had this dependency fix for wolfgang webots sim flying around.
> Webots sim dependency fix

- wolfgang_description/urdf/robot.urdf
See https://github.com/bit-bots/bitbots_misc/pull/186
> Remove camera optical frame from urdf.

- wolfgang_pybullet_sim/wolfgang_pybullet_sim/ros_interface.py
Should fix accelerometer in pybullet sim
https://github.com/bit-bots/wolfgang_robot/issues/81
> pybullet: fix accel

- wolfgang_webots_sim/wolfgang_webots_sim/webots_robot_controller.py
- wolfgang_webots_sim/wolfgang_webots_sim/webots_supervisor_controller.py
> webots: fix some errors in webots controller

- wolfgang_robocup_api/package.xml
- wolfgang_robocup_api/wolfgang_robocup_api/command_proxy.py
- wolfgang_webots_sim/wolfgang_webots_sim/webots_robot_controller.py
- Set joint velocities in proxy node
- Forward given velocity or use maximum defined in URDF. (As in old wolfgang_robocup_api)
[Screencast from 2023-03-13 14-34-36.webm](https://user-images.githubusercontent.com/34797331/224743379-d5b87696-3b0c-4d61-a311-006575d9e52e.webm)
[Screencast from 2023-03-13 16-05-55.webm](https://user-images.githubusercontent.com/34797331/224743433-06f1c790-47e2-4240-8f6c-55ed24aa7a31.webm)
> Fix proxy node send velocities

- wolfgang_robocup_api/docker/Dockerfile
- Add cyclone cpp package
- Set env variable
Closes #261
> Use cyclone dds in docker

- wolfgang_robocup_api/scripts/start.sh
> Start script: Fix team comm target_ip parameter

- wolfgang_robocup_api/docker/README.md
> Docker README: Fix IP

- wolfgang_robocup_api/package.xml
Add missing `topic_tools` dependency
> Add missing `topic_tools` dependency

- wolfgang_animations/package.xml
- wolfgang_description/package.xml
- wolfgang_moveit_config/package.xml
- wolfgang_pybullet_sim/package.xml
- wolfgang_webots_sim/package.xml
to allow for new features like conditional depends accoring to rep [0149].
We use this to differentiate between dependencies required on robots and in
the simulation.
[149]: https://www.ros.org/reps/rep-0149.html
> fix(package.xml): upgrade to version 3

- wolfgang_animations/animations/motion/cheering.json
Fixes: https://github.com/bit-bots/wolfgang_robot/issues/269
> Bug fix RShoulderroll cant handle values below 0

- wolfgang_robocup_api/docker/Dockerfile
- wolfgang_robocup_api/docker/entrypoint.sh
> Dockerfile: Use rosdep and migrate to ROS 2 iron

- wolfgang_robocup_api/docker/Dockerfile
- wolfgang_robocup_api/launch/record_bag.launch
- wolfgang_robocup_api/launch/robocup_teamplayer.launch
Use record ros bag launch from bitbots_utils
bit-bots/bitbots_misc/pull/190
> Use record ros bag launch from bitbots_utils
